### ISSUE TITLE
App cannot build

### ISSUE THREAD

**Issue by VladislavHacker** [nwjs-community/nw-builder#467]
Latest Version: v0.24.3
Using v0.24.3 (sdk)
Error: Unsupported NW.js version '0.24.3 (sdk)' for platform 'osx32'
    at /usr/local/lib/node_modules/nw-builder/lib/index.js:276:19
    at /usr/local/lib/node_modules/nw-builder/lib/index.js:781:16
    at /usr/local/lib/node_modules/nw-builder/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/usr/local/lib/node_modules/nw-builder/node_modules/lodash/lodash.js:3001:24)
    at /usr/local/lib/node_modules/nw-builder/node_modules/lodash/lodash.js:4913:18
    at Function.forEach (/usr/local/lib/node_modules/nw-builder/node_modules/lodash/lodash.js:9359:14)
    at NwBuilder._forEachPlatform (/usr/local/lib/node_modules/nw-builder/lib/index.js:780:7)
    at NwBuilder.platformFilesForVersion (/usr/local/lib/node_modules/nw-builder/lib/index.js:271:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by bramblex** [comment]
Just select your platform by -p.

for example:

macos: `nwbuild -p osx64`
linux: `nwbuild -p linux64` or `nwbuild -p linux32`
windows: `nwbuild -p win32`

**Comment by adam-lynch** [comment]
Yes, that's the fix. NW.js doesn't support osx 32 anymore. We might be updating the default not to include `osx32` soon. Thanks
