### ISSUE TITLE
"Unable to download Nwjs"

### ISSUE THREAD

**Issue by cmyers09** [nwjs-community/nw-builder#538]
This can be fixed on the users side by adding the option `downloadUrl: 'https://dl.nwjs.io/'` to your build script. This overwrites the default that uses HTTP.

_Originally posted by @schuhschuh in https://github.com/nwjs-community/nw-builder/issues/418#issuecomment-270895079_

How do I add download URL to my build script?  
I am trying to build my NW.js application and whenever I run my build script I get: "Unable to download Nwjs" error.

Here is my package.json:
```json {
  "name": "newapp",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "nw-react-scripts": "4.0.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^4.0.3",
    "react-select": "^4.3.1",
    "react-sortable-hoc": "^2.0.0",
    "uuid": "^8.3.2",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "nw-react-scripts start",
    "build": "nw-react-scripts build",
    "test": "nw-react-scripts test",
    "eject": "nw-react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "nw-react-app",
      "nw-react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "main": "index.html",
  "nwBuilder": {
    "//": "https://github.com/nwjs-community/nw-builder",
    "platforms": [
      "osx64",
      "win32",
      "win64"
    ],
    "version": "latest",
    "flavor": "normal",
    "buildDir": "./build",
    "cacheDir": "./cache",
    "macIcns": "./src/logo.icns"
  }
}
```
Here is my debug log:
```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle newapp@0.1.0~prebuild: newapp@0.1.0
6 info lifecycle newapp@0.1.0~build: newapp@0.1.0
7 verbose lifecycle newapp@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle newapp@0.1.0~build: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\cmyer\Desktop\nw-js-app\newapp\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Incredibuild;C:\Program Files\Git\cmd;C:\Users\cmyer\AppData\Local\Temp\Rar$EXa16572.16805\COMMON\COMMON;C:\Users\cmyer\AppData\Local\Temp\Rar$EXa16572.16805\COMMON\COMMON\Perl;C:\Program Files (x86)\nodejs\;C:\Users\cmyer\AppData\Local\Microsoft\WindowsApps;C:\Users\cmyer\.dotnet\tools;C:\Users\cmyer\AppData\Local\atom\bin;C:\Users\cmyer\AppData\Roaming\npm
9 verbose lifecycle newapp@0.1.0~build: CWD: C:\Users\cmyer\Desktop\nw-js-app\newapp
10 silly lifecycle newapp@0.1.0~build: Args: [ '/d /s /c', 'nw-react-scripts build' ]
11 silly lifecycle newapp@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle newapp@0.1.0~build: Failed to exec build script
13 verbose stack Error: newapp@0.1.0 build: `nw-react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid newapp@0.1.0
15 verbose cwd C:\Users\cmyer\Desktop\nw-js-app\newapp
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 1
22 error newapp@0.1.0 build: `nw-react-scripts build`
22 error Exit status 1
23 error Failed at the newapp@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by cmyers09** [comment]
I was able to solve this issue by:
1. Running in command line with administrator privilages instead of vs code and
2. Changing my package.json to:
```json{
  "name": "newapp",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "nw-react-scripts": "4.0.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "^4.0.3",
    "react-select": "^4.3.1",
    "react-sortable-hoc": "^2.0.0",
    "uuid": "^8.3.2",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "nw-react-scripts start",
    "build": "nw-react-scripts build",
    "test": "nw-react-scripts test",
    "eject": "nw-react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "nw-react-app",
      "nw-react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "main": "index.html",
  "nwBuilder": {
    "//": "https://github.com/nwjs-community/nw-builder",
    "platforms": [
      "osx64",
      "win32",
      "win64"
    ],
    "version": "latest",
    "flavor": "normal",
    "buildDir": "./build",
    "cacheDir": "./cache",
    "macIcns": "./src/logo.icns",
    "downloadURL": "https://dl.nwjs.io/"
  }
}
```
